mod_id=sfcr
mod_name=SuperFancyClouds:Reclassic
mod_group=com.rimo
mod_version=0.2.0
mod_author=Rimo
mod_description=A client/server side mod makes your Minecraft sky full of more stereoscopic and dynamic clouds.
minecraft_version=1.12.2
forge_version=14.23.5.2860
mappings_channel=snapshot
mappings_version=20180814-1.12
mod_mixin_configs=${mod_id}.mixins.json
mod_mixin_refmap=${mod_id}.refmap.json
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
